### ISSUE TITLE
creating members is inconsistent on Heroku

### ISSUE THREAD

**Issue by graysonwright** [wrightmhw/DFD#7]

**Comment by graysonwright** [comment]
Hey, @wrightmhw – I tracked this down using `git bisect`, and I think I found the problem. I left a few comments [here](https://github.com/wrightmhw/DFD/commit/329201af8f71b96e9f88a9711535f29254b7d194).

Also, you should [read about git bisect](http://robots.thoughtbot.com/git-bisect). It's awesome and makes your life a lot easier when something was working before but now it's not.

**Comment by wrightmhw** [comment]
![screen shot 2015-01-20 at 12 02 49 pm](https://cloud.githubusercontent.com/assets/5634398/5821740/5edc3a4e-a09c-11e4-8185-a0ddda0ecdef.png)
@graysonwright 
I fixed the `destroy` code I had before; but the routing is still bad. Seems like the id's cant be found?

**Comment by graysonwright** [comment]
Try to install the [binding_of_caller](https://rubygems.org/gems/binding_of_caller) gem, and then visit that page again – whenever you hit an error your app like that, it'll automatically give you a debugging prompt in the browser.

also, maybe try: `<%= link_to "Delete member", member_path(@member.id), :method => :delete %>`?

**Comment by wrightmhw** [comment]
Hey, @graysonwright. I had to change it to
`<li class="member-link"> <%= link_to "Delete member", member_path(@members.find(member.id)), :method => :delete %> </li>`

Does that make sense to you why we couldnt do the other ways?

**Comment by wrightmhw** [comment]
@graysonwright so.... I just dont quite understand why heroku is displaying like this right now

do I have to pay for it? Is this because it is snoozing? I dont see any css be loaded.
![screen shot 2015-01-20 at 3 12 07 pm](https://cloud.githubusercontent.com/assets/5634398/5825135/1dbf0102-a0b7-11e4-8dc0-4f184b91aa39.png)

**Comment by graysonwright** [comment]
Hey, Michael! Whenever something goes wrong on the page, check the JS console. Here's what I'm seeing:

![screenshot 2015-01-20 14 00 11](https://cloud.githubusercontent.com/assets/829576/5827100/ae8fe526-a0ac-11e4-85ef-4a0eb2bb9633.png)

Also, you should probably open another issue for the CSS problem, because it isn't related to deleting the members.

**Comment by graysonwright** [comment]
The CSS problem should be taken care of with #11.

**Comment by graysonwright** [comment]
This issue is solved with 53698f.

**Comment by wrightmhw** [comment]
^^ "issue solved with ####"...  This is a good workflow habit. Thanks!
